logo: itsmemari
title: Mariana Nascimento
heading: Mariana is a Brazilian interdisciplinary designer passionate about design, research & data
description: Site description
author: Mariana Nascimento

# exclude: ['README.md']