logo: itsmemari
title: Mariana Nascimento
heading: Hi! I’m Mariana, a multi-disciplinary designer passionate about design, research & data
description: Site description
author: Mariana Nascimento

# exclude: ['README.md']