logo: itsmemari
title: Mariana Nascimento
complement: Senior Product Designer
heading: Mariana is an independent experience designer focused on about design, research & data
description: Mariana's online portfolio page
author: Mariana Nascimento

# exclude: ['README.md']