logo: itsmemari
title: Mariana Sueiro
complement: Senior Product Designer
heading: Mariana Sueiro is an independent experience designer focused on research & data
description: Mariana Sueiro's online portfolio
author: Mariana Sueiro
url: "https://itsmemari.com"

# exclude: ['README.md']